### ISSUE TITLE
Invalid block was submitted: Invalid signature 

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/tfchain#102]
with unlocked wallet i tried to do wallet init naively to start with a new wallet i received that on the server 
## Steps
```
ahmed@ahmedheaven:/home/ahmed  $ tfchainc --addr http://192.168.21.124:23110 wallet
Wallet status:
Encrypted, Unlocked
Confirmed Balance:   100002080 TFT
Locked Balance:      0 TFT
Unconfirmed Delta:   + 0 TFT
BlockStakes:         3000 BS
ahmed@ahmedheaven:/home/ahmed  $ tfchainc --addr http://192.168.21.124:23110 wallet init
You have to provide a passphrase!
If you have an existing mnemonic you can use the recover wallet command instead.
Wallet passphrase: 
Reenter passphrase: 
API password: 
Error when encrypting wallet: error when calling /wallet/init: wallet is already encrypted, cannot encrypt again

```
## Stacktrace

```
goroutine 16 [running]:
runtime/debug.Stack(0x4446d7, 0x0, 0xc420183c50)
	/home/ahmed/go-dev/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/home/ahmed/go-dev/src/runtime/debug/stack.go:16 +0x22
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/build.Critical(0xc420183e38, 0x2, 0x2)
	/home/ahmed/gowork/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/build/critical.go:15 +0xa7
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/persist.(*Logger).Critical(0xc42025c360, 0xc420183e38, 0x2, 0x2)
	/home/ahmed/gowork/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/persist/log.go:38 +0xe0
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/blockcreator.(*BlockCreator).submitBlock(0xc420115340, 0x9c36016e64c1b2b4, 0x6aca93e0019c37b5, 0x324848bbf9c9a283, 0x167fec69fdc4299a, 0x5af82739, 0xda, 0x0, 0x0, 0xc4201d7400, ...)
	/home/ahmed/gowork/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/blockcreator/blockmanager.go:32 +0x24b
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/blockcreator.(*BlockCreator).SolveBlocks(0xc420115340)
	/home/ahmed/gowork/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/blockcreator/proofofblockstake.go:45 +0x336
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/blockcreator.New
	/home/ahmed/gowork/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/blockcreator/blockcreator.go:137 +0x652
Critical error: ERROR: an invalid block was submitted: invalid signature
Please submit a bug report here: https://github.com/rivine/rivine/issues
goroutine 16 [running]:
runtime/debug.Stack(0x4446d7, 0x0, 0xc420183c50)
	/home/ahmed/go-dev/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/home/ahmed/go-dev/src/runtime/debug/stack.go:16 +0x22
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/build.Critical(0xc420183e38, 0x2, 0x2)
	/home/ahmed/gowork/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/build/critical.go:15 +0xa7
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/persist.(*Logger).Critical(0xc42025c360, 0xc420183e38, 0x2, 0x2)
	/home/ahmed/gowork/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/persist/log.go:38 +0xe0
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/blockcreator.(*BlockCreator).submitBlock(0xc420115340, 0x9c36016e64c1b2b4, 0x6aca93e0019c37b5, 0x324848bbf9c9a283, 0x167fec69fdc4299a, 0x5af82758, 0xda, 0x0, 0x0, 0xc4201d66e0, ...)
	/home/ahmed/gowork/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/blockcreator/blockmanager.go:32 +0x24b
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/blockcreator.(*BlockCreator).SolveBlocks(0xc420115340)
	/home/ahmed/gowork/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/blockcreator/proofofblockstake.go:45 +0x336
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/blockcreator.New
	/home/ahmed/gowork/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/blockcreator/blockcreator.go:137 +0x652
Critical error: ERROR: an invalid block was submitted: invalid signature
Please submit a bug report here: https://github.com/rivine/rivine/issues

```

## versions
```
~ tfchaind version
Tfchain Daemon v1.0.5
Rivine Protocol v1.0.5
~ tfchainc version
Tfchain Client v1.0.5
```

**Comment by GlenDC** [comment]
I encountered the same issue, in a slightly different way, yesterday. Will look into this.

**Comment by GlenDC** [comment]
This bug happens because one signs with a nil-private key. The unlock fulfillment logic should prevent nil keys from being used. However, the real source of the bug is why we can reach this deep logic with a nil key. My guess to why this happens is because the wallet is locked and thus cannot give the key, however, if so, it should return an error when trying to get that key.

**Comment by GlenDC** [comment]
Solving this bug gives another panic when playing with constant locking/unlocking:

```
oroutine 66 [running]:
runtime/debug.Stack(0x11e9e87, 0xc4204edc98, 0xc4204edc60)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xb5
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x34
github.com/rivine/rivine/build.Critical(0xc4204ede40, 0x2, 0x2)
	/Users/glendc/go/src/github.com/rivine/rivine/build/critical.go:15 +0xa7
github.com/rivine/rivine/persist.(*Logger).Critical(0xc42030a6a0, 0xc4204ede40, 0x2, 0x2)
	/Users/glendc/go/src/github.com/rivine/rivine/persist/log.go:38 +0x11c
github.com/rivine/rivine/modules/blockcreator.(*BlockCreator).submitBlock(0xc420310000, 0x8a404d65b6748a8f, 0x554b3b713f867078, 0x826ce3034ec96524, 0x9002ab1a9555d5b8, 0x5b168dec, 0x10, 0x0, 0x0, 0xc420295a40, ...)
	/Users/glendc/go/src/github.com/rivine/rivine/modules/blockcreator/blockmanager.go:32 +0x29f
github.com/rivine/rivine/modules/blockcreator.(*BlockCreator).SolveBlocks(0xc420310000)
	/Users/glendc/go/src/github.com/rivine/rivine/modules/blockcreator/proofofblockstake.go:45 +0x3dd
created by github.com/rivine/rivine/modules/blockcreator.New
	/Users/glendc/go/src/github.com/rivine/rivine/modules/blockcreator/blockcreator.go:137 +0x897
Critical error: ERROR: an invalid block was submitted: The block stake used to generate block should be respent
Please submit a bug report here: https://github.com/rivine/rivine/issues
panic: Critical error: ERROR: an invalid block was submitted: The block stake used to generate block should be respent
Please submit a bug report here: https://github.com/rivine/rivine/issues


goroutine 66 [running]:
github.com/rivine/rivine/build.Critical(0xc4204ede40, 0x2, 0x2)
	/Users/glendc/go/src/github.com/rivine/rivine/build/critical.go:18 +0x121
github.com/rivine/rivine/persist.(*Logger).Critical(0xc42030a6a0, 0xc4204ede40, 0x2, 0x2)
	/Users/glendc/go/src/github.com/rivine/rivine/persist/log.go:38 +0x11c
github.com/rivine/rivine/modules/blockcreator.(*BlockCreator).submitBlock(0xc420310000, 0x8a404d65b6748a8f, 0x554b3b713f867078, 0x826ce3034ec96524, 0x9002ab1a9555d5b8, 0x5b168dec, 0x10, 0x0, 0x0, 0xc420295a40, ...)
	/Users/glendc/go/src/github.com/rivine/rivine/modules/blockcreator/blockmanager.go:32 +0x29f
github.com/rivine/rivine/modules/blockcreator.(*BlockCreator).SolveBlocks(0xc420310000)
	/Users/glendc/go/src/github.com/rivine/rivine/modules/blockcreator/proofofblockstake.go:45 +0x3dd
created by github.com/rivine/rivine/modules/blockcreator.New
	/Users/glendc/go/src/github.com/rivine/rivine/modules/blockcreator/blockcreator.go:137 +0x897
```
