### ISSUE TITLE
hang during ctrl-c

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#117]
While there may be many different causes, pasting my stack here:
tfchain version: v1.0.6-alpha-6
```
$ ./tfchaind --network testnet -M cgtwbe
Loading...
(0/6) Loading daemon of tfchain...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading explorer...
(4/6) Loading transaction pool...
(5/6) Loading wallet...
(6/6) Loading block creator...
Finished loading in 0.175456859 seconds
Rescanning consensus set...
Scanned to height 27399...
Done!
Caught stop signal, quitting...
Closing block creator...
Closing wallet...
Closing transaction pool...
Closing explorer...
Closing consensus set...
Closing gateway...
SIGQUIT: quit
PC=0x10592fb m=0 sigcode=0

goroutine 0 [idle]:
runtime.mach_semaphore_wait(0x2803, 0xe, 0xc420572000, 0x7ffeefbff500, 0x1021838, 0x18e8440, 0x7ffeefbff518, 0x10536d3, 0xffffffffffffffff, 0x0, ...)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/sys_darwin_amd64.s:540 +0xb
runtime.semasleep1(0xffffffffffffffff, 0x0)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/os_darwin.go:438 +0x52
runtime.semasleep.func1()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/os_darwin.go:457 +0x33
runtime.semasleep(0xffffffffffffffff, 0xc400000000)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/os_darwin.go:456 +0x44
runtime.notesleep(0x18e8cc8)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/lock_sema.go:167 +0xe9
runtime.stopm()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:1947 +0xe5
runtime.findrunnable(0xc420036f00, 0x0)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:2410 +0x50c
runtime.schedule()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:2536 +0x13b
runtime.park_m(0xc42025d680)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:2599 +0xb6
runtime.mcall(0x0)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:351 +0x5b

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc42026414c)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc420264140)
	/usr/local/Cellar/go/1.10/libexec/src/sync/waitgroup.go:129 +0x72
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/sync.(*ThreadGroup).Stop(0xc4202640e8, 0x0, 0x0)
	/Users/rob/workspace/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/sync/threadgroup.go:140 +0x12b
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).Close(0xc420264000, 0x0, 0x0)
	/Users/rob/workspace/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/gateway.go:185 +0x40
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon.StartDaemon.func2(0x15c2c60, 0xc420264000)
	/Users/rob/workspace/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon/daemon.go:260 +0x75
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon.StartDaemon(0x1552560, 0x7, 0x1000500, 0x100060000000000, 0x6168706c61, 0x0, 0x0, 0x1556f8c, 0xf, 0x15504f0, ...)
	/Users/rob/workspace/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon/daemon.go:393 +0xae6
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon.newStartDaemonCmd.func1(0xc420108fc0, 0xc4200b2700, 0x0, 0x4)
	/Users/rob/workspace/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon/commands.go:36 +0xbf
github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra.(*Command).execute(0xc420108fc0, 0xc4200c0100, 0x4, 0x4, 0xc420108fc0, 0xc4200c0100)
	/Users/rob/workspace/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420108fc0, 0x1, 0x156a9af, 0x34)
	/Users/rob/workspace/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420108fc0, 0xc420146e80, 0x15520eb)
	/Users/rob/workspace/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon.SetupDefaultDaemon(0x1552560, 0x7, 0x1000500, 0x100060000000000, 0x6168706c61, 0x154e8d8, 0x0, 0x1556f8c, 0xf, 0x15504f0, ...)
	/Users/rob/workspace/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/pkg/daemon/commands.go:159 +0xba0
main.main()
	/Users/rob/workspace/go/src/github.com/threefoldfoundation/tfchain/cmd/tfchaind/main.go:24 +0x33e

goroutine 19 [syscall]:
os/signal.signal_recv(0x15bdd60)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/sigqueue.go:139 +0xa7
os/signal.loop()
	/usr/local/Cellar/go/1.10/libexec/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/Cellar/go/1.10/libexec/src/os/signal/signal_unix.go:28 +0x41

goroutine 34 [sleep, 1272 minutes]:
time.Sleep(0x8817f9940821)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/time.go:102 +0x166
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/profile.StartContinuousProfile.func1(0x1552560, 0x7, 0x1000500, 0x100060000000000, 0x6168706c61, 0x1553034, 0x8)
	/Users/rob/workspace/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/profile/profile.go:110 +0x12a
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/profile.StartContinuousProfile
	/Users/rob/workspace/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/profile/profile.go:96 +0xe8

goroutine 30 [select, 6259 minutes, locked to thread]:
runtime.gopark(0x157ca90, 0x0, 0x1551234, 0x6, 0x18, 0x1)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc42021ef50, 0xc42009c840)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/signal_unix.go:549 +0x1c6
runtime.goexit()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361 +0x1

goroutine 238894 [IO wait]:
internal/poll.runtime_pollWait(0x1a7a470, 0x72, 0xc422827818)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42029c398, 0x72, 0xffffffffffffff00, 0x15bb420, 0x18075e0)
	/usr/local/Cellar/go/1.10/libexec/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc42029c398, 0xc422513b00, 0x8, 0x8)
	/usr/local/Cellar/go/1.10/libexec/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42029c380, 0xc422513b50, 0x8, 0x8, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.10/libexec/src/internal/poll/fd_unix.go:157 +0x1dc
net.(*netFD).Read(0xc42029c380, 0xc422513b50, 0x8, 0x8, 0xc420875e50, 0xc422827928, 0x108d872)
	/usr/local/Cellar/go/1.10/libexec/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42025a008, 0xc422513b50, 0x8, 0x8, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.10/libexec/src/net/net.go:176 +0x6a
io.ReadAtLeast(0x1a878b0, 0xc42025a008, 0xc422513b50, 0x8, 0x8, 0x8, 0x148d400, 0x1, 0xc422513b50)
	/usr/local/Cellar/go/1.10/libexec/src/io/io.go:309 +0x86
io.ReadFull(0x1a878b0, 0xc42025a008, 0xc422513b50, 0x8, 0x8, 0x8, 0x29, 0x0)
	/usr/local/Cellar/go/1.10/libexec/src/io/io.go:327 +0x58
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/encoding.ReadPrefix(0x1a878b0, 0xc42025a008, 0x10, 0x1010568, 0x14c6f60, 0x1532d60, 0x0, 0x1a878b0)
	/Users/rob/workspace/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/encoding/prefix.go:13 +0x97
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/encoding.ReadObject(0x1a878b0, 0xc42025a008, 0x14da9a0, 0xc420aa3940, 0x10, 0x0, 0x45d964b555)
	/Users/rob/workspace/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/encoding/prefix.go:28 +0x43
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).connectHandshake(0xc420264000, 0x15c18e0, 0xc42025a008, 0x68706c6101000600, 0x786cf4d00000061, 0xc637cc64, 0xc42078be40, 0x13, 0x157cb01, 0xc42214cd50, ...)
	/Users/rob/workspace/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:276 +0x3e4
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).managedConnect(0xc420264000, 0xc42010ad40, 0x14, 0x0, 0x0)
	/Users/rob/workspace/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peers.go:649 +0x2d5
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).managedPeerManagerConnect(0xc420264000, 0xc42010ad40, 0x14)
	/Users/rob/workspace/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peersmanager.go:13 +0x108
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).permanentPeerManager.func1(0xc42009c420, 0xc420264000, 0xc42010ad40, 0x14)
	/Users/rob/workspace/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peersmanager.go:147 +0xb9
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).permanentPeerManager
	/Users/rob/workspace/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/peersmanager.go:135 +0x45e

rax    0xe
rbx    0x18e8b80
rcx    0x7ffeefbff4b8
rdx    0x7ffeefbff538
rdi    0x2803
rsi    0x1
rbp    0x7ffeefbff4f0
rsp    0x7ffeefbff4b8
r8     0x3
r9     0x18e8440
r10    0x0
r11    0x246
r12    0x189dc6ef25bb0
r13    0x0
r14    0x0
r15    0x1056ac0
rip    0x10592fb
rflags 0x246
cs     0x7
fs     0x0
gs     0x0
MacBook-Pro-783:tfchaind rob$
```

**Comment by GlenDC** [comment]
Since latest code I do not think this is still happening in latest (master) code. Please re-open if encountered again. Sometimes it can take a minute or so to close, especially when just started the daemon, but closing it should, I haven't encountered a hang in ages since using latest codebase.
