### ISSUE TITLE
bridged: index out of range error for consensus module

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/tfchain#226]
https://github.com/threefoldfoundation/tfchain/blob/master_bridged/cmd/bridged/main.go

I've a tfchaind running on default ports rpc 23112
and another one 
`tfchaind--no-bootstrap--networkdevnet--api-addrlocalhost:23120--rpc-addrlocalhost:23113`
and hardcoded both in the bridged daemon 
```go
func GetDevnetBootstrapPeers() []modules.NetAddress {
  return []modules.NetAddress{
    "localhost:23112",
    "localhost:23113",
  }
}
```
but whenever i start it i get
```bash
~> ./bridged --rpc-addr localhost:23118 

2018/12/11 11:21:41 starting bridged v1.2.0+dev...
2018/12/11 11:21:41 loading network config, registering types and loading rivine transaction db (0/3)...
2018/12/11 11:21:41 loading rivine gateway module (1/3)...
2018/12/11 11:21:47 loading rivine consensus module (2/3)...
2018/12/11 11:21:47 Closing consensus module...
2018/12/11 11:21:47 Closing gateway module...
panic: runtime error: index out of range

goroutine 34 [running]:
github.com/threefoldfoundation/tfchain/vendor/github.com/threefoldtech/rivine/modules/consensus.stdBlockRuleHelper.minimumValidChildTimestamp(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ahmed/gowork/src/github.com/threefoldfoundation/tfchain/vendor/github.com/threefoldtech/rivine/modules/consensus/block_rules.go:30 +0x31b
github.com/threefoldfoundation/tfchain/vendor/github.com/threefoldtech/rivine/modules/consensus.(*ConsensusSet).computeConsensusChange(0xc0003d0000, 0xc0003da1c0, 0x0, 0x0, 0x0, 0xc0003b8440, 0x1, 0x1, 0x0, 0x0, ...)
        /home/ahmed/gowork/src/github.com/threefoldfoundation/tfchain/vendor/github.com/threefoldtech/rivine/modules/consensus/subscribe.go:61 +0x9c9
github.com/threefoldfoundation/tfchain/vendor/github.com/threefoldtech/rivine/modules/consensus.(*ConsensusSet).initializeSubscribe.func1(0xc0003da1c0, 0x9cb0d8, 0xc0003da1c0)
        /home/ahmed/gowork/src/github.com/threefoldfoundation/tfchain/vendor/github.com/threefoldtech/rivine/modules/consensus/subscribe.go:139 +0x1be
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/bbolt.(*DB).View(0xc0003d6000, 0xc00025f9c8, 0x0, 0x0)
        /home/ahmed/gowork/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/bbolt/db.go:708 +0x90
github.com/threefoldfoundation/tfchain/vendor/github.com/threefoldtech/rivine/modules/consensus.(*ConsensusSet).initializeSubscribe(0xc0003d0000, 0xa32420, 0xc0003b0540, 0x0, 0x0, 0x0, 0x0, 0xc0003b6540, 0xc00030e030, 0xc00025fa70)
        /home/ahmed/gowork/src/github.com/threefoldfoundation/tfchain/vendor/github.com/threefoldtech/rivine/modules/consensus/subscribe.go:97 +0xb6
github.com/threefoldfoundation/tfchain/vendor/github.com/threefoldtech/rivine/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0xc0003d0000, 0xa32420, 0xc0003b0540, 0x0, 0x0, 0x0, 0x0, 0xc0003b6540, 0x0, 0x0)
        /home/ahmed/gowork/src/github.com/threefoldfoundation/tfchain/vendor/github.com/threefoldtech/rivine/modules/consensus/subscribe.go:168 +0x161
github.com/threefoldfoundation/tfchain/pkg/persist.(*TransactionDB).SubscribeToConsensusSet(0xc00030e000, 0xa3ca60, 0xc0003d0000, 0xc000302100, 0x1a)
        /home/ahmed/gowork/src/github.com/threefoldfoundation/tfchain/pkg/persist/transactiondb.go:146 +0x140
main.(*Commands).Root.func1(0xc000146db0, 0xc0002be5a0, 0xc000302100, 0xc000302230, 0xa37760, 0xc000140a40)
        /home/ahmed/gowork/src/github.com/threefoldfoundation/tfchain/cmd/bridged/main.go:184 +0x6a5
created by main.(*Commands).Root
        /home/ahmed/gowork/src/github.com/threefoldfoundation/tfchain/cmd/bridged/main.go:144 +0x4e0
```

**Comment by xmonader** [comment]
wrong execution `--network devnet` was needed
