### ISSUE TITLE
Error after keeping bridge running for some time

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldfoundation/tfchain#372]
```
INFO [10-01|10:10:19.042] LightClient needs to start to sync       current_block=0 peers=[]
INFO [10-01|10:10:29.045] LightClient needs to start to sync       current_block=0 peers=[]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4901df1]

goroutine 8498 [running]:
github.com/threefoldfoundation/tfchain/vendor/github.com/ethereum/go-ethereum/les.(*clientHandler).synchronise(0xc0000dc580, 0xc002245e00)
	/Users/dylan/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/ethereum/go-ethereum/les/sync.go:160 +0x381
github.com/threefoldfoundation/tfchain/vendor/github.com/ethereum/go-ethereum/les.(*lightFetcher).newFetcherDistReqForSync.func3.1(0x4f6f8e0, 0xc002245e00, 0xc0000c61e0)
	/Users/dylan/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/ethereum/go-ethereum/les/fetcher.go:509 +0x92
created by github.com/threefoldfoundation/tfchain/vendor/github.com/ethereum/go-ethereum/les.(*lightFetcher).newFetcherDistReqForSync.func3
	/Users/dylan/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/ethereum/go-ethereum/les/fetcher.go:506 +0xb8
```

**Comment by DylanVerstraete** [comment]
related go ethereum issue: https://github.com/ethereum/go-ethereum/issues/20097

Should be fixed on master.

**Comment by DylanVerstraete** [comment]
Issue only occurs when syncing with a synced or in syncing progress bootnode.

**Comment by GlenDC** [comment]
Fixed in merged PR #367.
