### ISSUE TITLE
panic when stopping tfchain daemon

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain#64]
## how to reproduce

```bash
tfchaind -Megtcbw --agent="" &
sleep 3
tfchainc wallet stop
```

> (no need to unlock wallet in order to reproduce)

expected behavior: daemon should stop gracefully

actual behavior and output of it:

```
Loading...
(0/6) Loading daemon of tfchain...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading explorer...
(4/6) Loading transaction pool...
(5/6) Loading wallet...
(6/6) Loading block creator...
Finished loading in 0.251183487 seconds
Closing block creator...
Closing wallet...
Closing transaction pool...
Closing explorer...
Closing consensus set...
goroutine 66 [running]:
runtime/debug.Stack(0x1224887, 0xc420674c98, 0xc420674c60)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xb5
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x34
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/build.Critical(0xc420674d48, 0x2, 0x2)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/build/critical.go:15 +0xa7
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/explorer.(*Explorer).ProcessConsensusChange(0xc42021cd80, 0x6f0f2ef947532535, 0x7a88491c9ece32c4, 0x7c18d13e51f2f3a, 0xd9c8e6ab0d06674, 0x0, 0x0, 0x0, 0xc4203da460, 0x1, ...)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/explorer/update.go:199 +0x193
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).readlockUpdateSubscribers(0xc4202d6000, 0x0, 0x0, 0x0, 0xc420613f60, 0x1, 0x1)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/subscribe.go:85 +0x23c
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).managedAcceptBlock(0xc4202d6000, 0x21f190b72c8a72d7, 0x2a61e5dfa4165e3d, 0x7a86b3ad04757b66, 0xe999c974540adce3, 0x5ac00f7d, 0xe0, 0x0, 0x0, 0xc4205e1e50, ...)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/accept.go:265 +0x2e0
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc4202d6000, 0x1844240, 0xc4202b6760, 0x0, 0x0)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/synchronize.go:220 +0x492
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).(github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.managedReceiveBlocks)-fm(0x1844240, 0xc4202b6760, 0x0, 0x0)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/synchronize.go:397 +0x56
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).managedRPC(0xc4202b2000, 0xc42021f020, 0x13, 0x17b9909, 0xa, 0xc4201df160, 0x0, 0x0)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:66 +0x35e
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).RPC(0xc4202b2000, 0xc42021f020, 0x13, 0x17b9909, 0xa, 0xc4201df160, 0x0, 0x0)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:76 +0xd2
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc4202d6000, 0xc420675eb8, 0xc420675e40, 0xc420675e48, 0x0, 0x0)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/synchronize.go:528 +0x197
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc4202d6000, 0x0, 0x0)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/synchronize.go:549 +0x1dd
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.New.func1(0x1, 0xc4202d6000, 0xc4201deec0, 0x1845360, 0xc4202b2000)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/consensusset.go:171 +0x539
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.New
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/consensusset.go:164 +0x1275
Critical error: explorer update failed: database not open
Please submit a bug report here: https://github.com/rivine/rivine/issues
panic: Critical error: explorer update failed: database not open
Please submit a bug report here: https://github.com/rivine/rivine/issues


goroutine 66 [running]:
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/build.Critical(0xc420674d48, 0x2, 0x2)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/build/critical.go:18 +0x121
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/explorer.(*Explorer).ProcessConsensusChange(0xc42021cd80, 0x6f0f2ef947532535, 0x7a88491c9ece32c4, 0x7c18d13e51f2f3a, 0xd9c8e6ab0d06674, 0x0, 0x0, 0x0, 0xc4203da460, 0x1, ...)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/explorer/update.go:199 +0x193
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).readlockUpdateSubscribers(0xc4202d6000, 0x0, 0x0, 0x0, 0xc420613f60, 0x1, 0x1)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/subscribe.go:85 +0x23c
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).managedAcceptBlock(0xc4202d6000, 0x21f190b72c8a72d7, 0x2a61e5dfa4165e3d, 0x7a86b3ad04757b66, 0xe999c974540adce3, 0x5ac00f7d, 0xe0, 0x0, 0x0, 0xc4205e1e50, ...)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/accept.go:265 +0x2e0
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc4202d6000, 0x1844240, 0xc4202b6760, 0x0, 0x0)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/synchronize.go:220 +0x492
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).(github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.managedReceiveBlocks)-fm(0x1844240, 0xc4202b6760, 0x0, 0x0)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/synchronize.go:397 +0x56
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).managedRPC(0xc4202b2000, 0xc42021f020, 0x13, 0x17b9909, 0xa, 0xc4201df160, 0x0, 0x0)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:66 +0x35e
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway.(*Gateway).RPC(0xc4202b2000, 0xc42021f020, 0x13, 0x17b9909, 0xa, 0xc4201df160, 0x0, 0x0)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/gateway/rpc.go:76 +0xd2
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc4202d6000, 0xc420675eb8, 0xc420675e40, 0xc420675e48, 0x0, 0x0)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/synchronize.go:528 +0x197
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc4202d6000, 0x0, 0x0)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/synchronize.go:549 +0x1dd
github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.New.func1(0x1, 0xc4202d6000, 0xc4201deec0, 0x1845360, 0xc4202b2000)
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/consensusset.go:171 +0x539
created by github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus.New
	/Users/glendc/go/src/github.com/threefoldfoundation/tfchain/vendor/github.com/rivine/rivine/modules/consensus/consensusset.go:164 +0x1275
```

## version

```
$ tfchainc version
Tfchain Client v1.0.2

$ tfchaind version
Tfchain Daemon v1.0.2
Rivine Protocol v1.0.2
```

> Compiled from the `v1.0.2` branch.

## persistent files

[standard.zip](https://github.com/threefoldfoundation/tfchain/files/1922912/standard.zip)

**Comment by LeeSmet** [comment]
Fixed in rivine/rivine#391
